import Foundation

// MARK: - Display names for known symbols

extension TickerQuote {
    static let displayNames: [String: String] = {
        var names: [String: String] = [:]

        // MARK: US Mega Cap Stocks
        names["AAPL"] = "Apple"
        names["MSFT"] = "Microsoft"
        names["GOOGL"] = "Alphabet"
        names["GOOG"] = "Alphabet"
        names["AMZN"] = "Amazon"
        names["META"] = "Meta"
        names["NVDA"] = "Nvidia"
        names["TSLA"] = "Tesla"
        names["AVGO"] = "Broadcom"
        names["LLY"] = "Eli Lilly"
        names["JPM"] = "JPMorgan"
        names["V"] = "Visa"
        names["MA"] = "Mastercard"
        names["UNH"] = "UnitedHealth"
        names["JNJ"] = "Johnson & Johnson"
        names["WMT"] = "Walmart"
        names["PG"] = "Procter & Gamble"
        names["HD"] = "Home Depot"
        names["CVX"] = "Chevron"
        names["MRK"] = "Merck"
        names["ABBV"] = "AbbVie"
        names["PFE"] = "Pfizer"
        names["BAC"] = "Bank of America"
        names["KO"] = "Coca-Cola"
        names["PEP"] = "PepsiCo"
        names["XOM"] = "ExxonMobil"
        names["COST"] = "Costco"
        names["NFLX"] = "Netflix"
        names["CRM"] = "Salesforce"
        names["ADBE"] = "Adobe"
        names["AMD"] = "AMD"
        names["INTC"] = "Intel"
        names["QCOM"] = "Qualcomm"
        names["TXN"] = "Texas Instruments"
        names["ORCL"] = "Oracle"
        names["IBM"] = "IBM"
        names["CSCO"] = "Cisco"
        names["GE"] = "GE Aerospace"
        names["CAT"] = "Caterpillar"
        names["BA"] = "Boeing"
        names["GS"] = "Goldman Sachs"
        names["MS"] = "Morgan Stanley"
        names["BLK"] = "BlackRock"
        names["SPGI"] = "S&P Global"
        names["MCO"] = "Moody's"
        names["NOW"] = "ServiceNow"
        names["INTU"] = "Intuit"
        names["AMAT"] = "Applied Materials"
        names["LRCX"] = "Lam Research"
        names["MU"] = "Micron"
        names["ARM"] = "Arm Holdings"
        names["TSM"] = "TSMC"
        names["SMCI"] = "Super Micro"

        // MARK: US Tech / Growth
        names["UBER"] = "Uber"
        names["ABNB"] = "Airbnb"
        names["SHOP"] = "Shopify"
        names["SQ"] = "Block"
        names["PYPL"] = "PayPal"
        names["COIN"] = "Coinbase"
        names["HOOD"] = "Robinhood"
        names["PLTR"] = "Palantir"
        names["SNOW"] = "Snowflake"
        names["DDOG"] = "Datadog"
        names["CRWD"] = "CrowdStrike"
        names["ZS"] = "Zscaler"
        names["NET"] = "Cloudflare"
        names["MDB"] = "MongoDB"
        names["GTLB"] = "GitLab"
        names["HUBS"] = "HubSpot"
        names["TEAM"] = "Atlassian"
        names["OKTA"] = "Okta"
        names["TWLO"] = "Twilio"
        names["ZM"] = "Zoom"
        names["DOCU"] = "DocuSign"
        names["PATH"] = "UiPath"
        names["AI"] = "C3.ai"
        names["SOUN"] = "SoundHound"
        names["IONQ"] = "IonQ"

        // MARK: EU Stocks
        names["ASML"] = "ASML"
        names["ASML.AS"] = "ASML"
        names["SAP"] = "SAP"
        names["SAP.DE"] = "SAP"
        names["MC.PA"] = "LVMH"
        names["RMS.PA"] = "Hermès"
        names["OR.PA"] = "L'Oréal"
        names["AIR.PA"] = "Airbus"
        names["TTE.PA"] = "TotalEnergies"
        names["BNP.PA"] = "BNP Paribas"
        names["AXA.PA"] = "AXA"
        names["SU.PA"] = "Schneider Electric"
        names["DG.PA"] = "Vinci"
        names["ORA.PA"] = "Orange"
        names["CAP.PA"] = "Capgemini"
        names["DSY.PA"] = "Dassault Systèmes"
        names["SIE.DE"] = "Siemens"
        names["ALV.DE"] = "Allianz"
        names["MBG.DE"] = "Mercedes-Benz"
        names["BMW.DE"] = "BMW"
        names["VOW3.DE"] = "Volkswagen"
        names["BAYN.DE"] = "Bayer"
        names["DBK.DE"] = "Deutsche Bank"
        names["ADS.DE"] = "Adidas"
        names["NOVO-B.CO"] = "Novo Nordisk"
        names["NESN.SW"] = "Nestlé"
        names["ROG.SW"] = "Roche"
        names["NOVN.SW"] = "Novartis"
        names["AZN"] = "AstraZeneca"
        names["SHEL"] = "Shell"
        names["BP"] = "BP"
        names["HSBC"] = "HSBC"
        names["VOD"] = "Vodafone"

        // MARK: ETF — Broad Market
        names["SPY"] = "S&P 500"
        names["IVV"] = "S&P 500 (iShares)"
        names["VOO"] = "S&P 500 (Vanguard)"
        names["VTI"] = "Total US Market"
        names["ITOT"] = "Total US Market (iShares)"
        names["QQQ"] = "NASDAQ-100"
        names["QQQM"] = "NASDAQ-100 (mini)"
        names["DIA"] = "Dow Jones"
        names["IWM"] = "Russell 2000"
        names["VGK"] = "Europe Large Cap"
        names["EWQ"] = "France (CAC 40)"
        names["EWG"] = "Germany (DAX)"
        names["EWU"] = "United Kingdom"
        names["EWJ"] = "Japan (Nikkei)"
        names["MCHI"] = "China Large Cap"
        names["EEM"] = "Emerging Markets"
        names["VWO"] = "Emerging Markets (Vanguard)"
        names["ACWI"] = "All World"

        // MARK: ETF — Sector
        names["XLK"] = "S&P Tech"
        names["XLF"] = "S&P Financials"
        names["XLE"] = "S&P Energy"
        names["XLV"] = "S&P Healthcare"
        names["XLI"] = "S&P Industrials"
        names["XLC"] = "S&P Communication"
        names["XLY"] = "S&P Consumer Disc."
        names["XLP"] = "S&P Consumer Staples"
        names["XLRE"] = "S&P Real Estate"
        names["XLU"] = "S&P Utilities"
        names["XLB"] = "S&P Materials"

        // MARK: ETF — Thematic Tech
        names["SOXX"] = "Semiconductors"
        names["SMH"] = "Semiconductors (VanEck)"
        names["IGV"] = "Software"
        names["ARKK"] = "ARK Innovation"
        names["ARKG"] = "ARK Genomic"
        names["ARKW"] = "ARK Next Generation"
        names["ARKF"] = "ARK Fintech"
        names["WCLD"] = "Cloud Computing"
        names["SKYY"] = "Cloud Computing (First Trust)"
        names["CLOU"] = "Cloud Computing (Global X)"
        names["BOTZ"] = "Robotics & AI"
        names["ROBO"] = "Robotics & Automation"
        names["HACK"] = "Cybersecurity"
        names["BUG"] = "Cybersecurity (Global X)"
        names["CIBR"] = "Cybersecurity (First Trust)"
        names["FINX"] = "Fintech"
        names["GBTC"] = "Bitcoin (Grayscale)"
        names["IBIT"] = "Bitcoin (BlackRock)"
        names["FBTC"] = "Bitcoin (Fidelity)"

        // MARK: ETF — Bonds & Commodities
        names["TLT"] = "US 20Y Treasury"
        names["IEF"] = "US 7-10Y Treasury"
        names["SHY"] = "US 1-3Y Treasury"
        names["HYG"] = "High Yield Corporate"
        names["LQD"] = "Investment Grade Corp."
        names["GLD"] = "Gold"
        names["IAU"] = "Gold (iShares)"
        names["SLV"] = "Silver"
        names["VNQ"] = "Real Estate (REIT)"

        // MARK: Indices
        names["^GSPC"] = "S&P 500"
        names["^IXIC"] = "NASDAQ Composite"
        names["^DJI"] = "Dow Jones"
        names["^RUT"] = "Russell 2000"
        names["^VIX"] = "VIX Volatility"
        names["^FCHI"] = "CAC 40"
        names["^GDAXI"] = "DAX"
        names["^FTSE"] = "FTSE 100"
        names["^N225"] = "Nikkei 225"
        names["^HSI"] = "Hang Seng"
        names["^STOXX50E"] = "Euro Stoxx 50"
        names["^AEX"] = "AEX Amsterdam"
        names["^IBEX"] = "IBEX 35"
        names["^SSMI"] = "SMI Switzerland"
        names["^BFX"] = "BEL 20"
        names["^MIB"] = "FTSE MIB Italy"
        names["^OMX"] = "OMX Stockholm"
        names["^BSESN"] = "BSE Sensex"
        names["^AXJO"] = "ASX 200"

        // MARK: Forex
        names["EURUSD=X"] = "EUR/USD"
        names["GBPUSD=X"] = "GBP/USD"
        names["USDJPY=X"] = "USD/JPY"
        names["USDCHF=X"] = "USD/CHF"
        names["AUDUSD=X"] = "AUD/USD"
        names["USDCAD=X"] = "USD/CAD"
        names["NZDUSD=X"] = "NZD/USD"
        names["EURGBP=X"] = "EUR/GBP"
        names["EURJPY=X"] = "EUR/JPY"
        names["EURCHF=X"] = "EUR/CHF"
        names["GBPJPY=X"] = "GBP/JPY"
        names["USDSEK=X"] = "USD/SEK"
        names["USDNOK=X"] = "USD/NOK"
        names["USDMXN=X"] = "USD/MXN"
        names["USDBRL=X"] = "USD/BRL"
        names["USDINR=X"] = "USD/INR"
        names["USDCNY=X"] = "USD/CNY"
        names["USDPLN=X"] = "USD/PLN"
        names["USDTRY=X"] = "USD/TRY"

        // MARK: Crypto
        names["BTC-USD"] = "Bitcoin"
        names["ETH-USD"] = "Ethereum"
        names["SOL-USD"] = "Solana"
        names["BNB-USD"] = "BNB"
        names["XRP-USD"] = "XRP"
        names["DOGE-USD"] = "Dogecoin"
        names["ADA-USD"] = "Cardano"
        names["AVAX-USD"] = "Avalanche"
        names["DOT-USD"] = "Polkadot"
        names["LINK-USD"] = "Chainlink"
        names["UNI-USD"] = "Uniswap"
        names["LTC-USD"] = "Litecoin"
        names["BCH-USD"] = "Bitcoin Cash"
        names["ATOM-USD"] = "Cosmos"
        names["NEAR-USD"] = "NEAR Protocol"
        names["ARB-USD"] = "Arbitrum"
        names["OP-USD"] = "Optimism"
        names["SUI-USD"] = "Sui"
        names["APT-USD"] = "Aptos"
        names["FIL-USD"] = "Filecoin"
        names["ALGO-USD"] = "Algorand"

        return names
    }()
}
